### ISSUE TITLE
[Feature Request] Improve ESLint Warning Box Visibility for Blue Themes

### ISSUE THREAD

**Issue by xiaoxiaodek** [jbisits/penumbra-zed#4]
Thank you for the excellent work migrating this theme to Zed. I've noticed that in some cases, the background color changes to #0090FF, making the text difficult to read. I tried setting [conflict] to null, but the issue persists. Your attention to resolving this would be appreciated.

<img width="919" alt="c56f8a6e-fc76-49ba-af6c-5abb9885c7ea" src="https://github.com/user-attachments/assets/1255fc66-e55a-4d57-9e36-d7fe42e9474d">

**Comment by jbisits** [comment]
Thanks for raising this! I will try and get to it soon.

**Comment by jbisits** [comment]
I have submitted a PR with updates that should fix this issue. I think for your case you want to override `warning.background` but this should be fixed in v0.1.1 of the theme. If/when it is updated and all is fixed could you close this issue?

Thanks again!

**Comment by xiaoxiaodek** [comment]
Thanks a lot. This works. I found it's related to the hint.background params.
